import Christie from "../../assets/combatants/fighter/doa/christie.png";
import ChristieIcon from "../../assets/combatants/fighter/doa/christie-icon.png";
import ChristieWin from "../../assets/combatants/fighter/doa/christie-win.png";
import ChristieLose from "../../assets/combatants/fighter/doa/christie-lose.png";

import Helena from "../../assets/combatants/fighter/doa/helena.png";
import HelenaIcon from "../../assets/combatants/fighter/doa/helena-icon.png";
import HelenaWin from "../../assets/combatants/fighter/doa/helena-win.png";
import HelenaLose from "../../assets/combatants/fighter/doa/helena-lose.png";

import Hitomi from "../../assets/combatants/fighter/doa/hitomi.png";
import HitomiIcon from "../../assets/combatants/fighter/doa/hitomi-icon.png";
import HitomiWin from "../../assets/combatants/fighter/doa/hitomi-win.png";
import HitomiLose from "../../assets/combatants/fighter/doa/hitomi-lose.png";

import Lisa from "../../assets/combatants/fighter/doa/lisa.png";
import LisaIcon from "../../assets/combatants/fighter/doa/lisa-icon.png";
import LisaWin from "../../assets/combatants/fighter/doa/lisa-win.png";
import LisaLose from "../../assets/combatants/fighter/doa/lisa-lose.png";

import MarieRose from "../../assets/combatants/fighter/doa/marie-rose.png";
import MarieRoseIcon from "../../assets/combatants/fighter/doa/marie-rose-icon.png";
import MarieRoseWin from "../../assets/combatants/fighter/doa/marie-rose-win.png";
import MarieRoseLose from "../../assets/combatants/fighter/doa/marie-rose-lose.png";

export const seriesId = "Dead or Alive";

export default {
  christie: {
    seriesId,
    id: "christie",
    name: "Christie",
    description: ".",
    img: Christie,
    icon: ChristieIcon,
    opWinImg: ChristieWin,
    opLoseImg: ChristieLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "petite",
    eyeColor: "red",
    hairColor: "white",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "breasts",
    uniqueAttackText: ".",
    roughPlayLvl: -5,
    seductionResistance: 28,
    grapplingProwess: 22,
    tongueProwess: 32,
    touchProwess: 25,
    cockProwess: 15,
    vaginaProwess: 20,
    anusProwess: 15,
    touchResistance: 30,
    breastResistance: 25,
    mouthResistance: 32,
    cockResistance: 35,
    vaginaResistance: 15,
    anusResistance: 5,
    orgasmLimit: 3,
  },
  helena: {
    seriesId,
    id: "helena",
    name: "Helena",
    description: ".",
    img: Helena,
    icon: HelenaIcon,
    opWinImg: HelenaWin,
    opLoseImg: HelenaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "human",
    bodyShape: "busty",
    eyeColor: "yellow",
    hairColor: "blue",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 4,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "touch",
    prefTarget: "cock",
    uniqueAttackText: ".",
    roughPlayLvl: 10,
    seductionResistance: 35,
    grapplingProwess: 35,
    tongueProwess: 15,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 15,
    anusProwess: 10,
    touchResistance: 15,
    breastResistance: 25,
    mouthResistance: 25,
    cockResistance: 15,
    vaginaResistance: 25,
    anusResistance: 10,
    orgasmLimit: 3,
  },
  hitomi: {
    seriesId,
    id: "hitomi",
    name: "Hitomi",
    description: ".",
    img: Hitomi,
    icon: HitomiIcon,
    opWinImg: HitomiWin,
    opLoseImg: HitomiLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "youthful",
    eyeColor: "auburn",
    hairColor: "hazel",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "mouth",
    uniqueAttackText: ".",
    roughPlayLvl: -10,
    seductionResistance: 25,
    grapplingProwess: 35,
    tongueProwess: 25,
    touchProwess: 30,
    cockProwess: 15,
    vaginaProwess: 45,
    anusProwess: 15,
    touchResistance: 20,
    breastResistance: 25,
    mouthResistance: 20,
    cockResistance: 15,
    vaginaResistance: 25,
    anusResistance: 15,
    orgasmLimit: 3,
  },
  lisa: {
    seriesId,
    id: "lisa",
    name: "Lisa",
    description: ".",
    img: Lisa,
    icon: LisaIcon,
    opWinImg: LisaWin,
    opLoseImg: LisaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Erune",
    bodyShape: "soft",
    eyeColor: "gold",
    hairColor: "blue",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "mouth",
    uniqueAttackText: ".",
    roughPlayLvl: -10,
    seductionResistance: 40,
    grapplingProwess: 15,
    tongueProwess: 35,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 20,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 15,
    cockResistance: 15,
    vaginaResistance: 5,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  marieRose: {
    seriesId,
    id: "marieRose",
    name: "MarieRose",
    description: ".",
    img: MarieRose,
    icon: MarieRoseIcon,
    opWinImg: MarieRoseWin,
    opLoseImg: MarieRoseLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "petite",
    eyeColor: "purple",
    hairColor: "blonde",
    skinColor: "pale",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 1,
    prefAttack: "tongue",
    prefTarget: "anus",
    uniqueAttackText: ".",
    roughPlayLvl: 25,
    seductionResistance: 45,
    grapplingProwess: 35,
    tongueProwess: 45,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 25,
    anusProwess: 25,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 30,
    cockResistance: 45,
    vaginaResistance: 15,
    anusResistance: 15,
    orgasmLimit: 3,
  },
};
