import Asuka from "../../assets/combatants/fighter/tekken/asuka.png";
import AsukaIcon from "../../assets/combatants/fighter/tekken/asuka-icon.png";
import AsukaWin from "../../assets/combatants/fighter/tekken/asuka-win.png";
import AsukaLose from "../../assets/combatants/fighter/tekken/asuka-lose.png";

import Emilie from "../../assets/combatants/fighter/tekken/emilie.png";
import EmilieIcon from "../../assets/combatants/fighter/tekken/emilie-icon.png";
import EmilieWin from "../../assets/combatants/fighter/tekken/emilie-win.png";
import EmilieLose from "../../assets/combatants/fighter/tekken/emilie-lose.png";

import Nina from "../../assets/combatants/fighter/tekken/nina.png";
import NinaIcon from "../../assets/combatants/fighter/tekken/nina-icon.png";
import NinaWin from "../../assets/combatants/fighter/tekken/nina-win.png";
import NinaLose from "../../assets/combatants/fighter/tekken/nina-lose.png";

import Xiaoyu from "../../assets/combatants/fighter/tekken/xiaoyu.png";
import XiaoyuIcon from "../../assets/combatants/fighter/tekken/xiaoyu-icon.png";
import XiaoyuWin from "../../assets/combatants/fighter/tekken/xiaoyu-win.png";
import XiaoyuLose from "../../assets/combatants/fighter/tekken/xiaoyu-lose.png";

export const seriesId = "Tekken";

export default {
  asuka: {
    seriesId,
    id: "asuka",
    name: "Asuka",
    description:
      ".",
    img: Asuka,
    icon: AsukaIcon,
    opWinImg: AsukaWin,
    opLoseImg: AsukaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "gold",
    hairColor: "black",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 3,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "cock",
    uniqueAttackText: "Asukae.",
    roughPlayLvl: 10,
    seductionResistance: 40,
    grapplingProwess: 35,
    tongueProwess: 25,
    touchProwess: 30,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 20,
    touchResistance: 35,
    breastResistance: 45,
    mouthResistance: 40,
    cockResistance: 25,
    vaginaResistance: 45,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  emilie: {
    seriesId,
    id: "emilie",
    name: "Emilie",
    description:
      ".",
    img: Emilie,
    icon: EmilieIcon,
    opWinImg: EmilieWin,
    opLoseImg: EmilieLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "blue",
    hairColor: "white",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "touch",
    prefTarget: "vagina",
    uniqueAttackText:
      "Emilie.",
    roughPlayLvl: -10,
    seductionResistance: 25,
    grapplingProwess: 35,
    tongueProwess: 35,
    touchProwess: 30,
    cockProwess: 35,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 35,
    mouthResistance: 20,
    cockResistance: 25,
    vaginaResistance: 15,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  nina: {
    seriesId,
    id: "nina",
    name: "Nina",
    description:
      ".",
    img: Nina,
    icon: NinaIcon,
    opWinImg: NinaWin,
    opLoseImg: NinaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "brown",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "anus",
    prefTarget: "mouth",
    uniqueAttackText: ".",
    roughPlayLvl: 12,
    seductionResistance: 32,
    grapplingProwess: 28,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 35,
    vaginaProwess: 20,
    anusProwess: 35,
    touchResistance: 25,
    breastResistance: 35,
    mouthResistance: 20,
    cockResistance: 15,
    vaginaResistance: 15,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  xiaoyu: {
    seriesId,
    id: "xiaoyu",
    name: "Xiaoyu",
    description:
      "Xiaoyu.",
    img: Xiaoyu,
    icon: XiaoyuIcon,
    opWinImg: XiaoyuWin,
    opLoseImg: XiaoyuLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "red",
    hairColor: "white",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 3,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "vagina",
    uniqueAttackText:
      ".",
    roughPlayLvl: 10,
    seductionResistance: 32,
    grapplingProwess: 25,
    tongueProwess: 35,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 20,
    touchResistance: 35,
    breastResistance: 25,
    mouthResistance: 20,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
};
