import Akagi from "../../assets/combatants/battleship/akagi.png";
import AkagiIcon from "../../assets/combatants/battleship/akagi-icon.png";
import AkagiWin from "../../assets/combatants/battleship/akagi-win.png";
import AkagiLose from "../../assets/combatants/battleship/akagi-lose.png";

import Hibiki from "../../assets/combatants/battleship/hibiki.png";
import HibikiIcon from "../../assets/combatants/battleship/hibiki-icon.png";
import HibikiWin from "../../assets/combatants/battleship/hibiki-win.png";
import HibikiLose from "../../assets/combatants/battleship/hibiki-lose.png";

import Kaga from "../../assets/combatants/battleship/kaga.png";
import KagaIcon from "../../assets/combatants/battleship/kaga-icon.png";
import KagaWin from "../../assets/combatants/battleship/kaga-win.png";
import KagaLose from "../../assets/combatants/battleship/kaga-lose.png";

import maxSchultz from "../../assets/combatants/battleship/max-schultz.png";
import maxSchultzIcon from "../../assets/combatants/battleship/max-schultz-icon.png";
import maxSchultzWin from "../../assets/combatants/battleship/max-schultz-win.png";
import maxSchultzLose from "../../assets/combatants/battleship/max-schultz-lose.png";

import Shimakaze from "../../assets/combatants/battleship/shimakaze.png";
import ShimakazeIcon from "../../assets/combatants/battleship/shimakaze-icon.png";
import ShimakazeWin from "../../assets/combatants/battleship/shimakaze-win.png";
import ShimakazeLose from "../../assets/combatants/battleship/shimakaze-lose.png";

import Zuikaku from "../../assets/combatants/battleship/zuikaku.png";
import ZuikakuIcon from "../../assets/combatants/battleship/zuikaku-icon.png";
import ZuikakuWin from "../../assets/combatants/battleship/zuikaku-win.png";
import ZuikakuLose from "../../assets/combatants/battleship/zuikaku-lose.png";

export const seriesId = "Kantai Collection";

export default {
  akagi: {
    seriesId,
    id: "akagi",
    name: "Akagi",
    description: ". ",
    img: Akagi,
    icon: AkagiIcon,
    opWinImg: AkagiWin,
    opLoseImg: AkagiLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  hibiki: {
    seriesId,
    id: "hibiki",
    name: "Hibiki",
    description: ". ",
    img: Hibiki,
    icon: HibikiIcon,
    opWinImg: HibikiWin,
    opLoseImg: HibikiLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  kaga: {
    seriesId,
    id: "kaga",
    name: "Kaga",
    description: ". ",
    img: Kaga,
    icon: KagaIcon,
    opWinImg: KagaWin,
    opLoseImg: KagaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  maxSchultz: {
    seriesId,
    id: "maxSchultz",
    name: "Max Schultz",
    description: ". ",
    img: maxSchultz,
    icon: maxSchultzIcon,
    opWinImg: maxSchultzWin,
    opLoseImg: maxSchultzLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  shimakaze: {
    seriesId,
    id: "shimakaze",
    name: "Shimakaze",
    description: ". ",
    img: Shimakaze,
    icon: ShimakazeIcon,
    opWinImg: ShimakazeWin,
    opLoseImg: ShimakazeLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  zuikaku: {
    seriesId,
    id: "zuikaku",
    name: "Zuikaku",
    description: ". ",
    img: Zuikaku,
    icon: ZuikakuIcon,
    opWinImg: ZuikakuWin,
    opLoseImg: ZuikakuLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText: "xxxx.",
    roughPlayLvl: 20,
    seductionResistance: 25,
    grapplingProwess: 15,
    tongueProwess: 25,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
};
