import Cynthia from "../../assets/combatants/pokemon/cynthia.png";
import CynthiaIcon from "../../assets/combatants/pokemon/cynthia-icon.png";
import CynthiaWin from "../../assets/combatants/pokemon/cynthia-win.png";
import CynthiaLose from "../../assets/combatants/pokemon/cynthia-lose.png";

import Dawn from "../../assets/combatants/pokemon/dawn.png";
import DawnIcon from "../../assets/combatants/pokemon/dawn-icon.png";
import DawnWin from "../../assets/combatants/pokemon/dawn-win.png";
import DawnLose from "../../assets/combatants/pokemon/dawn-lose.png";

import Gloria from "../../assets/combatants/pokemon/gloria.png";
import GloriaIcon from "../../assets/combatants/pokemon/gloria-icon.png";
import GloriaWin from "../../assets/combatants/pokemon/gloria-win.png";
import GloriaLose from "../../assets/combatants/pokemon/gloria-lose.png";

import Green from "../../assets/combatants/pokemon/green.png";
import GreenIcon from "../../assets/combatants/pokemon/green-icon.png";
import GreenWin from "../../assets/combatants/pokemon/green-win.png";
import GreenLose from "../../assets/combatants/pokemon/green-lose.png";

import Hilda from "../../assets/combatants/pokemon/hilda.png";
import HildaIcon from "../../assets/combatants/pokemon/hilda-icon.png";
import HildaWin from "../../assets/combatants/pokemon/hilda-win.png";
import HildaLose from "../../assets/combatants/pokemon/hilda-lose.png";

import Jessie from "../../assets/combatants/pokemon/jessie.png";
import JessieIcon from "../../assets/combatants/pokemon/jessie-icon.png";
import JessieWin from "../../assets/combatants/pokemon/jessie-win.png";
import JessieLose from "../../assets/combatants/pokemon/jessie-lose.png";

import Lillie from "../../assets/combatants/pokemon/lillie.png";
import LillieIcon from "../../assets/combatants/pokemon/lillie-icon.png";
import LillieWin from "../../assets/combatants/pokemon/lillie-win.png";
import LillieLose from "../../assets/combatants/pokemon/lillie-lose.png";

import Marnie from "../../assets/combatants/pokemon/marnie.png";
import MarnieIcon from "../../assets/combatants/pokemon/marnie-icon.png";
import MarnieWin from "../../assets/combatants/pokemon/marnie-win.png";
import MarnieLose from "../../assets/combatants/pokemon/marnie-lose.png";

import May from "../../assets/combatants/pokemon/may.png";
import MayIcon from "../../assets/combatants/pokemon/may-icon.png";
import MayWin from "../../assets/combatants/pokemon/may-win.png";
import MayLose from "../../assets/combatants/pokemon/may-lose.png";

import Misty from "../../assets/combatants/pokemon/misty.png";
import MistyIcon from "../../assets/combatants/pokemon/misty-icon.png";
import MistyWin from "../../assets/combatants/pokemon/misty-win.png";
import MistyLose from "../../assets/combatants/pokemon/misty-lose.png";

import Moon from "../../assets/combatants/pokemon/moon.png";
import MoonIcon from "../../assets/combatants/pokemon/moon-icon.png";
import MoonWin from "../../assets/combatants/pokemon/moon-win.png";
import MoonLose from "../../assets/combatants/pokemon/moon-lose.png";

import Nessa from "../../assets/combatants/pokemon/nessa.png";
import NessaIcon from "../../assets/combatants/pokemon/nessa-icon.png";
import NessaWin from "../../assets/combatants/pokemon/nessa-win.png";
import NessaLose from "../../assets/combatants/pokemon/nessa-lose.png";

import NewSerena from "../../assets/combatants/pokemon/new-serena.png";
import NewSerenaIcon from "../../assets/combatants/pokemon/new-serena-icon.png";
import NewSerenaWin from "../../assets/combatants/pokemon/new-serena-win.png";
import NewSerenaLose from "../../assets/combatants/pokemon/new-serena-lose.png";

import Rosa from "../../assets/combatants/pokemon/rosa.png";
import RosaIcon from "../../assets/combatants/pokemon/rosa-icon.png";
import RosaWin from "../../assets/combatants/pokemon/rosa-win.png";
import RosaLose from "../../assets/combatants/pokemon/rosa-lose.png";

import Serena from "../../assets/combatants/pokemon/serena.png";
import SerenaIcon from "../../assets/combatants/pokemon/serena-icon.png";
import SerenaWin from "../../assets/combatants/pokemon/serena-win.png";
import SerenaLose from "../../assets/combatants/pokemon/serena-lose.png";

export const seriesId = "Pokémon";

export default {
  cynthia: {
    seriesId,
    id: "cynthia",
    name: "Cynthia Possible",
    description: ".",
    img: Cynthia,
    icon: CynthiaIcon,
    opWinImg: CynthiaWin,
    opLoseImg: CynthiaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "buxom",
    eyeColor: "light grey",
    hairColor: "white",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "mouth",
    uniqueAttackText:
      "Cynthia .",
    roughPlayLvl: 10,
    seductionResistance: 25,
    grapplingProwess: 35,
    tongueProwess: 34,
    touchProwess: 28,
    cockProwess: 25,
    vaginaProwess: 20,
    anusProwess: 15,
    touchResistance: 25,
    breastResistance: 40,
    mouthResistance: 20,
    cockResistance: 25,
    vaginaResistance: 25,
    anusResistance: 18,
    orgasmLimit: 3,
  },
  dawn: {
    seriesId,
    id: "dawn",
    name: "Dawn",
    description:
      ".",
    img: Dawn,
    icon: DawnIcon,
    opWinImg: DawnWin,
    opLoseImg: DawnLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "toned",
    eyeColor: "blue",
    hairColor: "red",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "touch",
    uniqueAttackText:
      "Dawn.",
    roughPlayLvl: 85,
    seductionResistance: 35,
    grapplingProwess: 35,
    tongueProwess: 35,
    touchProwess: 35,
    cockProwess: 20,
    vaginaProwess: 30,
    anusProwess: 15,
    touchResistance: 15,
    breastResistance: 30,
    mouthResistance: 34,
    cockResistance: 30,
    vaginaResistance: 25,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  gloria: {
    seriesId,
    id: "gloria",
    name: "Gloria",
    description:
      "Gloria.",
    img: Gloria,
    icon: GloriaIcon,
    opWinImg: GloriaWin,
    opLoseImg: GloriaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "blue",
    hairColor: "white",
    skinColor: "pale",
    height: 3,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "touch",
    prefTarget: "touch",
    uniqueAttackText: "Gloria.",
    roughPlayLvl: 5,
    seductionResistance: 42,
    grapplingProwess: 30,
    tongueProwess: 35,
    touchProwess: 48,
    cockProwess: 25,
    vaginaProwess: 45,
    anusProwess: 45,
    touchResistance: 48,
    breastResistance: 25,
    mouthResistance: 35,
    cockResistance: 25,
    vaginaResistance: 35,
    anusResistance: 15,
    orgasmLimit: 3,
  },
  jessie: {
    seriesId,
    id: "jessie",
    name: "Jessie",
    description:
      "Jessie.",
    img: Jessie,
    icon: JessieIcon,
    opWinImg: JessieWin,
    opLoseImg: JessieLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "toned",
    eyeColor: "green",
    hairColor: "red",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "mouth",
    uniqueAttackText:
      "Jessie.",
    roughPlayLvl: -5,
    seductionResistance: 45,
    grapplingProwess: 38,
    tongueProwess: 25,
    touchProwess: 25,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 25,
    // -- resistance is ability to endure pleasure, 1 - 100
    touchResistance: 35,
    breastResistance: 20,
    mouthResistance: 32,
    cockResistance: 15,
    vaginaResistance: 45,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  green: {
    seriesId,
    id: "green",
    name: "Green",
    description:
      "Green.",
    img: Green,
    icon: GreenIcon,
    opWinImg: GreenWin,
    opLoseImg: GreenLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "human",
    bodyShape: "curvy",
    eyeColor: "hazel",
    hairColor: "aubrun",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 1,
    anusSize: 2,
    throatSize: 1,
    prefAttack: "touch",
    prefTarget: "breasts",
    uniqueAttackText: "Green.",
    roughPlayLvl: -15,
    seductionResistance: 35,
    grapplingProwess: 40,
    tongueProwess: 35,
    touchProwess: 35,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 10,
    touchResistance: 15,
    breastResistance: 45,
    mouthResistance: 20,
    cockResistance: 35,
    vaginaResistance: 15,
    anusResistance: 50,
    orgasmLimit: 3,
  },
  hilda: {
    seriesId,
    id: "hilda",
    name: "Hilda",
    description:
      "Hilda .",
    img: Hilda,
    icon: HildaIcon,
    opWinImg: HildaWin,
    opLoseImg: HildaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "curvaceous",
    eyeColor: "blue",
    hairColor: "blonde",
    skinColor: "pale green",
    height: 1,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 1,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "cock",
    uniqueAttackText:
      "Hilda.",
    roughPlayLvl: 12,
    seductionResistance: 35,
    grapplingProwess: 40,
    tongueProwess: 40,
    touchProwess: 20,
    cockProwess: 25,
    vaginaProwess: 15,
    anusProwess: 25,
    touchResistance: 35,
    breastResistance: 25,
    mouthResistance: 35,
    cockResistance: 25,
    vaginaResistance: 30,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  lillie: {
    seriesId,
    id: "lillie",
    name: "Lillie",
    description:
      "Lillie.",
    img: Lillie,
    icon: LillieIcon,
    opWinImg: LillieWin,
    opLoseImg: LillieLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "tight",
    eyeColor: "green",
    hairColor: "auburn-white",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "anus",
    uniqueAttackText:
      "Lillie .",
    roughPlayLvl: -5,
    seductionResistance: 42,
    grapplingProwess: 45,
    tongueProwess: 42,
    touchProwess: 20,
    cockProwess: 35,
    vaginaProwess: 25,
    anusProwess: 35,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 25,
    anusResistance: 15,
    orgasmLimit: 3,
  },
  marnie: {
    seriesId,
    id: "marnie",
    name: "Marnie",
    description:
      "Marnie.",
    img: Marnie,
    icon: MarnieIcon,
    opWinImg: MarnieWin,
    opLoseImg: MarnieLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "youthful",
    eyeColor: "green",
    hairColor: "ginger",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 2,
    prefAttack: "touch",
    prefTarget: "vagina",
    uniqueAttackText:
      "Marnie.",
    roughPlayLvl: 15,
    seductionResistance: 52,
    grapplingProwess: 42,
    tongueProwess: 25,
    touchProwess: 45,
    cockProwess: 15,
    vaginaProwess: 25,
    anusProwess: 45,
    touchResistance: 55,
    breastResistance: 45,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 45,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  may: {
    seriesId,
    id: "may",
    name: "May",
    description:
      "May.",
    img: May,
    icon: MayIcon,
    opWinImg: MayWin,
    opLoseImg: MayLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "toned",
    eyeColor: "black",
    hairColor: "black",
    skinColor: "pale",
    height: 3,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "breasts",
    uniqueAttackText:
      "May.",
    roughPlayLvl: 10,
    seductionResistance: 38,
    grapplingProwess: 50,
    tongueProwess: 50,
    touchProwess: 20,
    cockProwess: 15,
    vaginaProwess: 20,
    anusProwess: 20,
    touchResistance: 45,
    breastResistance: 25,
    mouthResistance: 25,
    cockResistance: 15,
    vaginaResistance: 52,
    anusResistance: 38,
    orgasmLimit: 3,
  },
  misty: {
    seriesId,
    id: "misty",
    name: "Misty",
    description:
      "Misty.",
    img: Misty,
    icon: MistyIcon,
    opWinImg: MistyWin,
    opLoseImg: MistyLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "blue",
    hairColor: "light grey",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "tongue",
    prefTarget: "vagina",
    uniqueAttackText:
      "Misty .",
    roughPlayLvl: -10,
    seductionResistance: 35,
    grapplingProwess: 25,
    tongueProwess: 55,
    touchProwess: 20,
    cockProwess: 35,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 35,
    mouthResistance: 20,
    cockResistance: 15,
    vaginaResistance: 45,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  moon: {
    seriesId,
    id: "moon",
    name: "Moon",
    description:
      "Moon.",
    img: Moon,
    icon: MoonIcon,
    opWinImg: MoonWin,
    opLoseImg: MoonLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "brown",
    hairColor: "black",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 3,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "touch",
    prefTarget: "mouth",
    uniqueAttackText: "Moon tuns her small quivering breasts over xxxx's face.",
    roughPlayLvl: 12,
    seductionResistance: 42,
    grapplingProwess: 38,
    tongueProwess: 25,
    touchProwess: 40,
    cockProwess: 35,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 15,
    mouthResistance: 20,
    cockResistance: 15,
    vaginaResistance: 35,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  Nessa: {
    seriesId,
    id: "Nessa",
    name: "Nessa",
    description: "Nessa.",
    img: Nessa,
    icon: NessaIcon,
    opWinImg: NessaWin,
    opLoseImg: NessaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "red",
    hairColor: "brown",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "touch",
    uniqueAttackText: "Nessa.",
    roughPlayLvl: 10,
    seductionResistance: 42,
    grapplingProwess: 35,
    tongueProwess: 35,
    touchProwess: 40,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 20,
    touchResistance: 35,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 45,
    anusResistance: 20,
    orgasmLimit: 3,
  },
  newSerena: {
    seriesId,
    id: "newSerena",
    name: "Serena",
    description:
      "Serena.",
    img: NewSerena,
    icon: NewSerenaIcon,
    opWinImg: NewSerenaWin,
    opLoseImg: NewSerenaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "dark grey",
    hairColor: "blonde",
    skinColor: "fair",
    height: 1,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 1,
    throatSize: 1,
    prefAttack: "tongue",
    prefTarget: "vagina",
    uniqueAttackText:
      "Serena.",
    roughPlayLvl: 12,
    seductionResistance: 35,
    grapplingProwess: 35,
    tongueProwess: 35,
    touchProwess: 30,
    cockProwess: 25,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 45,
    breastResistance: 35,
    mouthResistance: 40,
    cockResistance: 25,
    vaginaResistance: 35,
    anusResistance: 32,
    orgasmLimit: 3,
  },
  rosa: {
    seriesId,
    id: "rosa",
    name: "Rosa",
    description:
      "Rosa .",
    img: Rosa,
    icon: RosaIcon,
    opWinImg: RosaWin,
    opLoseImg: RosaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "small",
    eyeColor: "green",
    hairColor: "dark brown",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 3,
    prefAttack: "touch",
    prefTarget: "breasts",
    uniqueAttackText: "Rosa gropes xxxx's tits expertly.",
    roughPlayLvl: 10,
    seductionResistance: 35,
    grapplingProwess: 45,
    tongueProwess: 25,
    touchProwess: 40,
    cockProwess: 15,
    vaginaProwess: 30,
    anusProwess: 20,
    touchResistance: 25,
    breastResistance: 25,
    mouthResistance: 40,
    cockResistance: 15,
    vaginaResistance: 31,
    anusResistance: 22,
    orgasmLimit: 3,
  },
  serena: {
    seriesId,
    id: "serena",
    name: "Serena",
    description:
      "Serena.",
    img: Serena,
    icon: SerenaIcon,
    opWinImg: SerenaWin,
    opLoseImg: SerenaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "gold",
    hairColor: "black",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 3,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "cock",
    uniqueAttackText: "Serena .",
    roughPlayLvl: 10,
    seductionResistance: 40,
    grapplingProwess: 35,
    tongueProwess: 25,
    touchProwess: 30,
    cockProwess: 15,
    vaginaProwess: 35,
    anusProwess: 20,
    touchResistance: 35,
    breastResistance: 45,
    mouthResistance: 40,
    cockResistance: 25,
    vaginaResistance: 45,
    anusResistance: 20,
    orgasmLimit: 3,
  },
};
