import Anna from "../../assets/combatants/disney/anna.png";
import AnnaIcon from "../../assets/combatants/disney/anna-icon.png";
import AnnaWin from "../../assets/combatants/disney/anna-win.png";
import AnnaLose from "../../assets/combatants/disney/anna-lose.png";

import Ariel from "../../assets/combatants/disney/ariel.png";
import ArielIcon from "../../assets/combatants/disney/ariel-icon.png";
import ArielWin from "../../assets/combatants/disney/ariel-win.png";
import ArielLose from "../../assets/combatants/disney/ariel-lose.png";

import Aurora from "../../assets/combatants/disney/aurora.png";
import AuroraIcon from "../../assets/combatants/disney/aurora-icon.png";
import AuroraWin from "../../assets/combatants/disney/aurora-win.png";
import AuroraLose from "../../assets/combatants/disney/aurora-lose.png";

import Belle from "../../assets/combatants/disney/belle.png";
import BelleIcon from "../../assets/combatants/disney/belle-icon.png";
import BelleWin from "../../assets/combatants/disney/belle-win.png";
import BelleLose from "../../assets/combatants/disney/belle-lose.png";

import Elsa from "../../assets/combatants/disney/elsa.png";
import ElsaIcon from "../../assets/combatants/disney/elsa-icon.png";
import ElsaWin from "../../assets/combatants/disney/elsa-win.png";
import ElsaLose from "../../assets/combatants/disney/elsa-lose.png";

import Jasmine from "../../assets/combatants/disney/jasmine.png";
import JasmineIcon from "../../assets/combatants/disney/jasmine-icon.png";
import JasmineWin from "../../assets/combatants/disney/jasmine-win.png";
import JasmineLose from "../../assets/combatants/disney/jasmine-lose.png";

import Megara from "../../assets/combatants/disney/megara.png";
import MegaraIcon from "../../assets/combatants/disney/megara-icon.png";
import MegaraWin from "../../assets/combatants/disney/megara-win.png";
import MegaraLose from "../../assets/combatants/disney/megara-lose.png";

import Mulan from "../../assets/combatants/disney/mulan.png";
import MulanIcon from "../../assets/combatants/disney/mulan-icon.png";
import MulanWin from "../../assets/combatants/disney/mulan-win.png";
import MulanLose from "../../assets/combatants/disney/mulan-lose.png";

import Rapunzel from "../../assets/combatants/disney/rapunzel.png";
import RapunzelIcon from "../../assets/combatants/disney/rapunzel-icon.png";
import RapunzelWin from "../../assets/combatants/disney/rapunzel-win.png";
import RapunzelLose from "../../assets/combatants/disney/rapunzel-lose.png";

export const seriesId = "League of Legends";

export default {
  anna: {
    seriesId,
    id: "anna",
    name: "Anna",
    description:
      ".",
    img: Anna,
    icon: AnnaIcon,
    opWinImg: AnnaWin,
    opLoseImg: AnnaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "buxom",
    eyeColor: "gold",
    hairColor: "black",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 3,
    vaginaSize: 2,
    anusSize: 1,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "mouth",
    uniqueAttackText:
      "Anna.",
    roughPlayLvl: 10,
    seductionResistance: 55,
    grapplingProwess: 48,
    tongueProwess: 34,
    touchProwess: 48,
    cockProwess: 25,
    vaginaProwess: 50,
    anusProwess: 35,
    touchResistance: 28,
    breastResistance: 40,
    mouthResistance: 34,
    cockResistance: 30,
    vaginaResistance: 52,
    anusResistance: 36,
    orgasmLimit: 3,
  },
  ariel: {
    seriesId,
    id: "ariel",
    name: "Ariel",
    description:
      "A.",
    img: Ariel,
    icon: ArielIcon,
    opWinImg: ArielWin,
    opLoseImg: ArielLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "toned",
    eyeColor: "red",
    hairColor: "black",
    skinColor: "pale",
    height: 3,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "touch",
    uniqueAttackText:
      "Ariel.",
    roughPlayLvl: 25,
    seductionResistance: 45,
    grapplingProwess: 55,
    tongueProwess: 45,
    touchProwess: 35,
    cockProwess: 40,
    vaginaProwess: 30,
    anusProwess: 35,
    touchResistance: 25,
    breastResistance: 30,
    mouthResistance: 44,
    cockResistance: 30,
    vaginaResistance: 45,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  aurora: {
    seriesId,
    id: "aurora",
    name: "Aurora",
    description:
      ".",
    img: Aurora,
    icon: AuroraIcon,
    opWinImg: AuroraWin,
    opLoseImg: AuroraLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "petite",
    eyeColor: "pink",
    hairColor: "blue",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 1,
    vaginaSize: 1,
    anusSize: 2,
    throatSize: 1,
    prefAttack: "touch",
    prefTarget: "touch",
    uniqueAttackText: "Aurora .",
    roughPlayLvl: 5,
    seductionResistance: 55,
    grapplingProwess: 60,
    tongueProwess: 35,
    touchProwess: 58,
    cockProwess: 35,
    vaginaProwess: 45,
    anusProwess: 45,
    touchResistance: 60,
    breastResistance: 32,
    mouthResistance: 35,
    cockResistance: 38,
    vaginaResistance: 35,
    anusResistance: 45,
    orgasmLimit: 3,
  },
  jasmine: {
    seriesId,
    id: "jasmine",
    name: "Jasmine",
    description:
      ".",
    img: Jasmine,
    icon: JasmineIcon,
    opWinImg: JasmineWin,
    opLoseImg: JasmineLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "green",
    hairColor: "black",
    skinColor: "bronze",
    height: 3,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 3,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "vagina",
    prefTarget: "cock",
    uniqueAttackText:
      "Jasmine.",
    roughPlayLvl: 15,
    seductionResistance: 50,
    grapplingProwess: 60,
    tongueProwess: 45,
    touchProwess: 25,
    cockProwess: 35,
    vaginaProwess: 55,
    anusProwess: 35,
    touchResistance: 32,
    breastResistance: 40,
    mouthResistance: 32,
    cockResistance: 45,
    vaginaResistance: 45,
    anusResistance: 38,
    orgasmLimit: 3,
  },
  belle: {
    seriesId,
    id: "belle",
    name: "Belle",
    description:
      ".",
    img: Belle,
    icon: BelleIcon,
    opWinImg: BelleWin,
    opLoseImg: BelleLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "human",
    bodyShape: "hourglass",
    eyeColor: "green",
    hairColor: "red",
    skinColor: "fair",
    height: 2,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "touch",
    prefTarget: "breasts",
    uniqueAttackText: "Belle.",
    roughPlayLvl: -5,
    seductionResistance: 62,
    grapplingProwess: 65,
    tongueProwess: 35,
    touchProwess: 62,
    cockProwess: 45,
    vaginaProwess: 45,
    anusProwess: 30,
    touchResistance: 65,
    breastResistance: 45,
    mouthResistance: 40,
    cockResistance: 55,
    vaginaResistance: 35,
    anusResistance: 50,
    orgasmLimit: 3,
  },
  elsa: {
    seriesId,
    id: "elsa",
    name: "Elsa",
    description:
      ".",
    img: Elsa,
    icon: ElsaIcon,
    opWinImg: ElsaWin,
    opLoseImg: ElsaLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "curvaceous",
    eyeColor: "blue",
    hairColor: "blonde",
    skinColor: "pale",
    height: 2,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 1,
    anusSize: 2,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "cock",
    uniqueAttackText:
      ".",
    roughPlayLvl: 12,
    seductionResistance: 55,
    grapplingProwess: 48,
    tongueProwess: 48,
    touchProwess: 30,
    cockProwess: 25,
    vaginaProwess: 35,
    anusProwess: 25,
    touchResistance: 35,
    breastResistance: 55,
    mouthResistance: 50,
    cockResistance: 35,
    vaginaResistance: 30,
    anusResistance: 45,
    orgasmLimit: 3,
  },
  megara: {
    seriesId,
    id: "megara",
    name: "Megara",
    description:
      ".",
    img: Megara,
    icon: MegaraIcon,
    opWinImg: MegaraWin,
    opLoseImg: MegaraLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "muscular",
    eyeColor: "gold",
    hairColor: "white",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 2,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 3,
    prefAttack: "tongue",
    prefTarget: "anus",
    uniqueAttackText: "Megara.",
    roughPlayLvl: 15,
    seductionResistance: 62,
    grapplingProwess: 65,
    tongueProwess: 62,
    touchProwess: 40,
    cockProwess: 35,
    vaginaProwess: 32,
    anusProwess: 35,
    touchResistance: 42,
    breastResistance: 50,
    mouthResistance: 60,
    cockResistance: 35,
    vaginaResistance: 35,
    anusResistance: 45,
    orgasmLimit: 3,
  },
  mulan: {
    seriesId,
    id: "mulan",
    name: "Mulan Fortune",
    description:
      ".",
    img: Mulan,
    icon: MulanIcon,
    opWinImg: MulanWin,
    opLoseImg: MulanLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "blue",
    hairColor: "red",
    skinColor: "fair",
    height: 3,
    penisSize: 0,
    breastSize: 5,
    vaginaSize: 2,
    anusSize: 3,
    throatSize: 2,
    prefAttack: "touch",
    prefTarget: "vagina",
    uniqueAttackText:
      ".",
    roughPlayLvl: 15,
    seductionResistance: 45,
    grapplingProwess: 55,
    tongueProwess: 35,
    touchProwess: 55,
    cockProwess: 25,
    vaginaProwess: 25,
    anusProwess: 45,
    touchResistance: 50,
    breastResistance: 45,
    mouthResistance: 40,
    cockResistance: 25,
    vaginaResistance: 45,
    anusResistance: 25,
    orgasmLimit: 3,
  },
  rapunzel: {
    seriesId,
    id: "rapunzel",
    name: "Rapunzel",
    description:
      ".",
    img: Rapunzel,
    icon: RapunzelIcon,
    opWinImg: RapunzelWin,
    opLoseImg: RapunzelLose,
    gender: "female",
    isWoman: true,
    hasCock: false,
    race: "Human",
    bodyShape: "busty",
    eyeColor: "blue",
    hairColor: "blue",
    skinColor: "pale",
    height: 3,
    penisSize: 0,
    breastSize: 4,
    vaginaSize: 2,
    anusSize: 2,
    throatSize: 2,
    prefAttack: "tongue",
    prefTarget: "breasts",
    uniqueAttackText:
      ".",
    roughPlayLvl: -10,
    seductionResistance: 58,
    grapplingProwess: 52,
    tongueProwess: 50,
    touchProwess: 22,
    cockProwess: 35,
    vaginaProwess: 25,
    anusProwess: 28,
    touchResistance: 45,
    breastResistance: 55,
    mouthResistance: 25,
    cockResistance: 28,
    vaginaResistance: 52,
    anusResistance: 38,
    orgasmLimit: 3,
  },
};
